# Generated by Django 3.1.3 on 2020-12-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='played_in', to='filmweb.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed', to='filmweb.person'),
        ),
    ]
