# Generated by Django 3.1.3 on 2020-12-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0003_country_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='filmweb.studio'),
            preserve_default=False,
        ),
    ]
